### ISSUE TITLE
SMD and Irrigation at beginning of simulation run exceptionally high

### ISSUE THREAD

**Issue by oliver-michels** [UMEP-dev/SuPy#25] opened 2021-02-04 16:13 UTC
Dear Ting

Thank you for your answer on my previous question, it works really well!

Something else came up a week ago, but I didn't have to time to post it until now. 

When SMD is modelled, the initial SMD value is very high, no matter when the simulation period starts. 
I did two runs, one run with ten years and one run with only the year 2015. Please find below the ten year figure, where SMD starts at ~30 this is in June.  (note 2015, where SMD seems normal, after SuPy calibrated) 

<img width="988" alt="SMD ten year" src="https://user-images.githubusercontent.com/63778850/106921090-f0f7b980-670b-11eb-9f32-e1486de0bd03.png">

and then a figure from the second run plus the first few rows of the df_output['SMD'], in the year 2015. Again SMD starts out at 30, which is too high for my data (Sorry, I turned the Precipitation upside down, I think it looks better :D)

<img width="991" alt="2015" src="https://user-images.githubusercontent.com/63778850/106921161-08cf3d80-670c-11eb-85f6-cc5b8b19327b.png">
<img width="442" alt="2015 output" src="https://user-images.githubusercontent.com/63778850/106921225-1a184a00-670c-11eb-8a9f-6da6b04c49c2.png">

Is there a df_state variable I missed to adjust or is this something in your code?

Lastly I also attached a ten year figure for irrigation, which seems to have the same issue as SMD (might be related?)
<img width="979" alt="Irrigation ten years" src="https://user-images.githubusercontent.com/63778850/106921257-243a4880-670c-11eb-9eac-3f391a7229a3.png">

Best wishes
Oliver

**Comment by sunt05** [comment] 2021-02-04 21:11
Hi Oliver, it might be better to see your initial conditions before we can address this issue. Are the settings the same as in your repo of this case? we may extend our discussion there to be more problem-focused.

**Comment by oliver-michels** [comment] 2021-02-04 23:50
I optimised the settings as much as possible here is everything I have set under df_state and these are the settings I am going to be using for my research simulations (well, except if there is anything that needs to be changed)

<img width="743" alt="Screenshot 2021-02-05 at 00 49 00" src="https://user-images.githubusercontent.com/63778850/106969923-1ad0d080-674c-11eb-823b-a541207fd37c.png">
<img width="743" alt="Screenshot 2021-02-05 at 00 49 11" src="https://user-images.githubusercontent.com/63778850/106969929-1d332a80-674c-11eb-875c-3aac46af73c5.png">

**Comment by oliver-michels** [comment] 2021-02-08 16:32
Quick update on this issue, I found the solution for the early spike in SMD, it's whenever there is a difference between the values set in "soilstorecap" and initial values in "soilstore_id". 

Kind regards
Oliver

**Comment by sunt05** [comment] 2021-02-08 16:39
Great to know you found the cause! (sorry I've on other threads these days and didn't get a chance to look into this.)

Then we may close this issue?

**Comment by oliver-michels** [comment] 2021-02-08 16:40
Yes, definitely!

This also fixed the early spike in Irrigation, please feel free to close this issue.

Best wishes
Oliver

**Closed** 2021-02-08 16:43 UTC
