### ISSUE TITLE
Latest version os Suews requesting for SUEWS_SPARTACUS.nml and gridlayout files

### ISSUE THREAD

**Issue by phemiobe** [UMEP-dev/SuPy#72] opened 2022-11-30 15:35 UTC
Hello,
Before now I have got no problem with running SuPy, but with the introduction of version supy: 2022.9.22, it keeps requesting for a SUEWS_SPARTACUS  file as well as a gridlayout file. Could anyone please clarify this new additional files and what they provides. I could see sample SUEWS spartacus file here (https://suews.readthedocs.io/en/latest/input_files/SS_input/SS_input.html#suews-spartacus-nml) but I can find as sample gridlaout file.

here is the error
1. /scratch/20202815/SUEWS/ICUC_run/prepare/SUEWS_SPARTACUS.nml does not exists!
2. SuPy - ERROR - /scratch/20202815/SUEWS_Dublin/prepare/GridLayout.nml does not exists!
Thank you

**Comment by sunt05** [comment] 2022-11-30 16:16
Please find the latest compatible input files here: https://github.com/UMEP-dev/SuPy/tree/master/src/supy/sample_run

**Comment by phemiobe** [comment] 2022-12-01 10:55
Many thanks Sunt05, this is helpful

**Comment by sunt05** [comment] 2022-12-01 10:59
Great to know it's useful - if the issue is fixed, please close it. thanks!

**Closed** 2022-12-01 11:07 UTC
