### ISSUE TITLE
Varying results / NaN for 'T2' in different grid cells

### ISSUE THREAD

**Issue by fbriegel** [UMEP-dev/SuPy#36] opened 2021-09-29 11:14 UTC
Dear all,
I run SuPy for multiple grid cells (> 200) and I am interested in the 'T2' output. However, SuPy returns only NaN for 'T2' for some grid cells. The initial grid cell states differ in surface fraction, building and tree heights, roughness and zero displacement length, frontal area index, and population density. Forcing data are the same for all grid cells. I attached the corresponding pickle files with two exemplary grid cells as zip file.

SuPy runs without any errors.

Thank you.
Ferdi

**Screenshots**
Initial state differences of grid cells:
```
## surface fraction
>> df_state.loc[:, 'sfr'] 

ind_dim   (0,)   (1,)  (2,)   (3,)   (4,)  (5,)   (6,)
grid                                                  
170      0.353  0.106     0  0.247  0.294   0.0  0.000
171      0.241  0.335     0  0.294  0.128   0.0  0.002

## tree and building heights
>> df_state.loc[:, ['dectreeh','evetreeh','bldgh']]

var     dectreeh evetreeh  bldgh
ind_dim        0        0      0
grid                            
170         7.18     7.18  11.67
171         8.33     8.33  13.77

## roughness and zero displacement length
>> df_state.loc[:, ['z0m_in','zdm_in']]

var     z0m_in zdm_in
ind_dim      0      0
grid                 
170       1.18  10.68
171       1.36  20.78

## frontal area index
>> df_state.loc[:, ['faibldg','faidectree','faievetree']]

var     faibldg faidectree faievetree
ind_dim       0          0          0
grid                                 
170        0.12       0.09       0.09
171        0.21       0.22       0.22
```
Output:
```
df_output_suews.loc[:, 'T2'].isna()
Out[41]: 
grid  datetime           
170   2006-01-01 02:00:00     True
      2006-01-01 03:00:00     True
      2006-01-01 04:00:00     True
      2006-01-01 05:00:00     True
      2006-01-01 06:00:00     True
 
171   2006-12-31 19:00:00    False
      2006-12-31 20:00:00    False
      2006-12-31 21:00:00    False
      2006-12-31 22:00:00    False
      2006-12-31 23:00:00    False
Name: T2, Length: 17516, dtype: bool
```

**Additional context**
Version:
```
SuPy versions
-------------
supy: 2021.7.22 
supy_driver: 2021a2

=================
SYSTEM DEPENDENCY

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.7.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.17763
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : en
LOCALE           : None.None

pandas           : 1.2.4
numpy            : 1.20.1
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.0.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : 4.0.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.8
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : 1.4.7
tables           : None
tabulate         : None
xarray           : 0.17.0
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1
```
[GitHub_Issue.zip](https://github.com/UMEP-dev/SuPy/files/7251260/GitHub_Issue.zip)

**Comment by sunt05** [comment] 2021-09-30 13:16
Hi @fbriegel , sorry to learn the T2 issue.
I had a look at your results (thanks for your detailed report and files: very considerate) and found the issue was caused by the small FAI in your grid 170: 
a small FAI along with other morphological settings would lead SUEWS to use the MOST scheme to near surface diagnostic calculations rather than RSL (see [here](https://github.com/UMEP-dev/SUEWS/blob/4783ad4438850ebeb79ef210cc5a57298c2cef22/SUEWS-SourceCode/src/suews_phys_rslprof.f95#L195-L196) for details); so, as you can see, the `zdm` of grid 170 is much higher than 2 m – anything below `zdm` makes no sense under the MOST framework – and hence the `NaN`s in your results.

To proceed for valid T2 results, please adjust your frontal area index values in grid 170 (I notice those for trees are rather small: i.e. < 0.1). 

Hope the above is helpful to you.

**Comment by fbriegel** [comment] 2021-10-01 12:09
Hi Ting,

thank you for the fast response and the explanations. It helped a lot to understand the behavior of SUEWS.
I changed the FAI value to 0.2 and indeed, it worked for grid cell 170 (but not for other ones - e.g. 168 see below). 

So, if I am right, the problem with T2 predictions is given by the dfinition of `flag_RSL` which depends on FAI, land cover fractions and building heights. This means that there are several ways to make SUEWS use the MOST scheme. Using the MOST scheme, on the other hand, leads to `NaN` values below `zdm`.  
Could it be a solution to set `zdm` to e.g. 1, if land cover fractions of buildings or FAI is low? As the impact of buildings is possibly negligible in this case?

E.g. grid cells 168 and 169:
```
>> df_state.loc[:, 'sfr'] 

ind_dim   (0,)   (1,)  (2,)   (3,)   (4,)  (5,)   (6,)
grid                                                  
168      0.244  0.076     0  0.115  0.565   0.0  0.000
169      0.378  0.077     0  0.031  0.514   0.0  0.000
170      0.353  0.106     0  0.247  0.294   0.0  0.000
171      0.241  0.335     0  0.294  0.128   0.0  0.002

>>df_state.loc[:, ['faibldg','faidectree','faievetree']]

var     faibldg faidectree faievetree
ind_dim       0          0          0
grid                                 
168        0.04       0.04       0.04
169        0.01       0.01       0.01
170        0.12       0.09       0.09
171        0.21       0.22       0.22

>>df_state.loc[:, ['dectreeh','evetreeh','bldgh']]

var     dectreeh evetreeh  bldgh
ind_dim        0        0      0
grid                            
168         6.54     6.54  10.89
169         5.09     5.09  12.04
170         7.18     7.18  11.67
171         8.33     8.33  13.77
```

Even using 0.2 for FAI leads to `NaN`. 
However, using the regular FAI values and setting `zdm` to 1, when FAI or land cover fractions getting to small, works for almost all grid cells.

Thanks,
Ferdi

**Comment by sunt05** [comment] 2021-10-01 18:39
Hi Ferdi, 
you can certainly do so – setting `zdm` to 1 – to avoid the numerical issue leading to `NAN` in T2. 
However, physically it depends on the environment to model: you need to justify if such a number is appropriate in your case.
Similarly, the setting of FAI may need to be well justified/considered.
Eventually, it is the interpretations of your simulation results that matters: if the settings, or any other input, are invalid, even though you get numerical results, then the results might not be useful as you would expect.

As such, please reconsider the choice of the parameter values.
If you deem they are valid but SUEWS produce crazy values, please do get in touch; and I'm happy to work with you to resolve the issues at the model side.

Good luck!

Ting

**Comment by fbriegel** [comment] 2021-10-04 08:48
Hi Ting,

thank you for this. 
I am mainly interessted in T2. I will check sensitvity and validity of the affected grid cells with varing `zdm` and FAI values. 
I will let you know if I run into any other issue.

Thanks,
Ferdi

**Comment by fbriegel** [comment] 2021-11-17 08:17
Dear Ting,
I wanted to ask if there are any new findings regarding the issue? 
Thanks,
Ferdi

**Comment by sunt05** [comment] 2021-11-17 08:24
Hi Ferdi,
I have no more new findings regarding the issues discussed above. 
If you have more questions/concerns, please let me know. Otherwise, please consider to close this issue. 

Thanks!
Ting

**Comment by suegrimmond** [comment] 2021-11-17 09:45
Doesn’t the problem still exist? -Or there needs to be something added to the manual to indicate what to do

**Comment by fbriegel** [comment] 2021-11-17 09:58
Yes, the problem still exists.

**Comment by sunt05** [comment] 2021-11-17 11:39
Hi Ferdi, 
I just had another look at your results and re-ran your case: except for the low wind speed I mentioned above, nothing new I can think of to explain the "abnormal" values.
Let's take grid 204 in a winter with the issue for example (hint: the plot below can be produced by [`supy.util.plot_rsl`](https://supy.readthedocs.io/en/latest/api/supy.util/supy.util.plot_rsl.html#supy.util.plot_rsl)):

![6bcff17e-01d2-4829-a7db-c32b25d7cb3a](https://user-images.githubusercontent.com/1802656/142192109-d5f54255-8c86-4021-aed7-75cc258f6984.png)

You can see the wind speed diagnosed by SUEWS (or more precisely, the RSL scheme) is quite low (<~0.1 m s-1) in the urban canopy, which may cause issues in other diagnostic variables (e.g., T2). And this is a common issue- low wind speed leads to unexpected diagnostics-for almost all PBL-related diagnostic schemes, including the RSL scheme in SUEWS.

So my suggestions would be:
1) double-check your forcing data and measurement height (currently I see a `z=35 m` is set in your case): see if they are appropriate for your case. To me, a forcing wind speed=0.3 [m s-1] at z=35 [m agl] would certainly lead the model to some issues. 
2) double-check your urban morphology settings (building height, frontal area index, etc).
And I think 1) is a major issue in this case.

Please let me know if more updates.

Best,
Ting

**Comment by fbriegel** [comment] 2021-11-18 08:22
Dear Ting,

thanky you for this.
I will check it next week and let you know.
Best,
Ferdi

**Closed** 2023-02-05 02:43 UTC
Labels: RSL, no-issue-activity
